### ISSUE TITLE
Send notification to the subscribers fails every time

### ISSUE THREAD

**Issue by vicvega83** [webmaxru/node-red-contrib-web-push#8] opened 2021-08-28 15:32 UTC
Hello,
I'm using this in Node Red 12 LTS running on a raspberry pi, and I'm trying to implement the basic demo flow: 
I can succesfully subscribe from different browsers and devices, but everytime I try to push a notification, it fails on all recipients.
Is there anywhere I could look to dig into the issue ?
I don't know if it can be of any help, but I'm also getting the error:

`"Unknown context store 'storeInFile' specified. Using default store.`
But looks like the permanent context is workng just fine: I see the folder it creates with the saved information, and tried
 sending notifications without subscribers, and it correctly gives me the error that there are none.

Thank you for your time

**Comment by bartbutenaers** [comment] 2021-08-28 16:44
Hi @vicvega83,

> But looks like the permanent context is workng just fine: I see the folder it creates with the saved information

So when you go to the Context sidebar tab (on the right in the flow editor), you see - under Flow - all the subscriptions.  Is that correct?  I mean as an array withe the name 'pushSubscriptions'.

**Comment by vicvega83** [comment] 2021-08-28 17:02
Hi Bart !
thanks for replying!
Yes I do
![context](https://user-images.githubusercontent.com/35502338/131225320-8cc771f7-6dbe-4847-93ed-95e57cf9f514.png)

**Comment by bartbutenaers** [comment] 2021-08-28 17:11
You say it fails on all recpients.  Does this mean you see an error?

**Comment by vicvega83** [comment] 2021-08-28 17:13
Yes, the node "send notifications to the subscribers" reports : 0 sent, 2 failed (I' currently testing both from desktop and mobile)

**Comment by bartbutenaers** [comment] 2021-08-28 17:22
Hmmm it is quite some time ago that I have been experimenting with Maxim's nodes.  I have written a more  extended subscription manager function node for my [node-red-contrib-ui-web-push](https://github.com/bartbutenaers/node-red-contrib-ui-web-push) nodes.  The input and output are different, so you cannot simply replace it by my function node!  

But if I remember correctly, I have added some extra code, because all root cause exceptions were swallowed.  Due to that I was - at the time being - also wondering about the root cause, and needed extra logging...

I will try to have a look whether I can give you that code snippet.  Will get back to you later...

**Comment by vicvega83** [comment] 2021-08-28 17:27
Thanks Bart!
I was puzzled by your sentence.

`The input and output are different, so you cannot simply replace it by my function node!`

until I realized I'm actually using your  node-red-contrib-ui-web-push nodes... maybe we should move there :)

**Comment by bartbutenaers** [comment] 2021-08-28 17:41
Fine for me.  You can close this issue and create a new one in my repository...

**Closed as completed** 2021-08-28 18:06 UTC
